name: Update

on:
  schedule:
    - cron: "0 18 * * 0"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +%d.%m.%Y)"
    - name: Update with wget
      continue-on-error: true
      run: |
        rm -rf docs.samsungknox.com
        wget -m -np -E -k -p -e robots=off https://docs.samsungknox.com
    - name: Add files and commit
      uses: EndBug/add-and-commit@v7
      with:
        author_name: github-actions
        author_email: 41898282+github-actions[bot]@users.noreply.github.com
        message: 'Update ${{ steps.date.outputs.date }}'
        add: '.'
        remove: '-f *.apk'
    - name: Update badge
      uses: RubbaBoy/BYOB@v1.2.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NAME: Update
        ICON: 'https://raw.githubusercontent.com/google/material-design-icons/master/src/action/update/materialicons/24px.svg'
        LABEL: 'Updated at'
        COLOR: 00FF00
        STATUS: ${{ steps.date.outputs.date }} UTC
